zuul:
     ignored-services: '*' 
     sensitiveHeaders: Cookie,Set-Cookie
     routes:
           movie-catalog-service: /catalog-service/**
           auth-server : /auth-server/**
eureka:
     client:
           registerWithEureka: true
           fetchRegistry: true
           serviceUrl:
               defaultZone: http://localhost:8761/eureka/
     instance:
           prefer-ip-address: true