spring:
  application:
     name: eureka-service
     
server:    
   port: 8085
     
eureka:
    client:
      registerWithEureka: false
      fetchRegistry: false
      server:
        waitTimeInMsWhenSyncEmpty: 0
        
zuul:
  prefix: /api
  routes:
    db-service:
      path: /db-service/**
      url: http://localhost:8084
    stock-service:
      path: /stock-service/**
      url: http://localhost:8083
  
  