spring:
  application:
     name: db-service
     
server:    
   port: 8084
     
eureka:
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8085/eureka
    instance:
        hostname: localhost
  
  